version: 1.0.{build}
image: Ubuntu1804

clone_folder: /home/appveyor/ansible-win-ping-appveyor-job${APPVEYOR_BUILD_VERSION}

environment:
  PIPENV_VERBOSITY: -1

install:
  - uname -a
  - sudo apt update
  - sudo apt install -y cpu-checker
  - sudo kvm-ok
  - source $HOME/venv3.8/bin/activate
  - python3.8 --version
  - pip3.8 --version
  - pip3.8 --disable-pip-version-check -q install pipenv
  - pipenv --version
  - pipenv --bare sync
  - pipenv run molecule --version
  - pipenv run ansible --version
  - wget -q https://releases.hashicorp.com/vagrant/2.2.13/vagrant_2.2.13_x86_64.deb
  - sudo apt install ./vagrant_2.2.13_x86_64.deb
  - vagrant --version
  - vboxmanage --version

build: false

# before_test:
#   - ROLE_NAME=$(basename $PWD)
#   - cd ..
#   - cp -r $ROLE_NAME $ROLE_NAME-job${APPVEYOR_JOB_NUMBER}
#   - cd $ROLE_NAME-job${APPVEYOR_JOB_NUMBER}

test_script:
  - pipenv run molecule test

after_test:
  - rm -rf artifacts
  - mkdir artifacts
  - find "$HOME/VirtualBox VMs" -name Logs -exec cp -rp {} artifacts/Vbox_Logs \;
  - cp -rp ~/.cache/molecule artifacts/cache_molecule

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'

artifacts:
  - path: artifacts
