version: 1.0.{build}
image: Ubuntu1604

environment:
  PIPENV_VERBOSITY: -1

install:
  - sudo apt install -y python3.8 python3-pip
  - python3.8 --version
  - python3.8 -m pip --version
  - python3.8 -m pip install pipenv
  - pipenv --version
  - pipenv --bare sync
  - pipenv run molecule --version
  - pipenv run ansible --version
  - wget -q https://releases.hashicorp.com/vagrant/2.2.13/vagrant_2.2.13_x86_64.deb
  - sudo apt install ./vagrant_2.2.13_x86_64.deb
  - vagrant --version
  - vboxmanage --version

build: false

before_test:
  - pipenv run molecule create

test_script:
  - pipenv run molecule test --destroy never

after_test:
  - rm -rf artifacts
  - mkdir artifacts
  - find "$HOME/VirtualBox VMs" -name Logs -exec cp -rp {} artifacts/Vbox_Logs \;
  - cp -rp ~/.cache/molecule artifacts/cache_molecule

on_finish:
  - pipenv run molecule destroy
  - rm -rf ~/.cache/molecule

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'

artifacts:
  - path: artifacts
