version: 1.0.{build}
image: Ubuntu1604

install:
  - source $HOME/venv3.8/bin/activate
  - python3 --version
  - pip3 --version
  - pip3 --disable-pip-version-check install pipenv
  - pipenv --version
  - pipenv --bare sync
  - sudo apt install https://releases.hashicorp.com/vagrant/2.2.13/vagrant_2.2.13_x86_64.deb

build: false

before_test:
  - pipenv run molecule create

test_script:
  - pipenv run molecule test --destroy never

on_finish:
  - pipenv run molecule destroy
