version: 1.0.{build}

environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Linux
  APPVEYOR_BUILD_WORKER_CLOUD: moe Docker
  PIPENV_VERBOSITY: -1
  ROLE_DIR: ${APPVEYOR_PROJECT_NAME}-job${APPVEYOR_JOB_ID}

install:
  - sudo apt update
  - sudo apt install -y cpu-checker
  - sudo kvm-ok
  - source $HOME/venv3.8/bin/activate
  - pip3.8 --disable-pip-version-check -q install pipenv
  - pipenv --bare sync
  - wget -q https://releases.hashicorp.com/vagrant/2.2.13/vagrant_2.2.13_x86_64.deb
  - sudo apt install ./vagrant_2.2.13_x86_64.deb
  - echo -e "\e[33m***** Print all versions\e[0m"
  - uname -a
  - python3.8 --version
  - pip3.8 --version
  - pipenv --version
  - pipenv run molecule --version
  - pipenv run ansible --version
  - vagrant --version
  - vboxmanage --version

build: false

before_test:
  # Move all files in subfoler $ROLE_DIR to avoid name collision in ~/.cache/molecule
  - mkdir $ROLE_DIR
  - shopt -s extglob dotglob
  - mv !($ROLE_DIR) $ROLE_DIR

test_script:
  - cd $ROLE_DIR
  - pipenv run molecule test

after_test:
  - mkdir artifacts
  - find "$HOME/VirtualBox VMs" -name Logs -exec cp -rp {} artifacts/Vbox_Logs \;
  - cp -rp ~/.cache/molecule artifacts/cache_molecule

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'

artifacts:
  - path: $ROLE_DIR/artifacts
